#!/usr/bin/env node
const Lead = require('./lead.js');
const LeadCollection = require('./LeadCollection.js');

const lead_collection = new LeadCollection();
const leads = LeadCollection.parseJsonFromLeadsFile('leads.json');

lead_collection.initializeLeadsAsLeadObjects(leads);

// Lead.all_sorted_by_date_desc.each do |lead|
//   Lead.store_lead_if_valid(lead)
// end

// Lead.update_change_log
// Lead.create_valid_leads_file
// Lead.output_summary_to_cli
// Lead.output_change_log_file_info
// const leadsArr = [];
// const data = fs.readFileSync('leads.json', 'utf-8');
// const leads = JSON.parse(data).leads;

// leads.forEach(lead => {
//   leadsArr.push(lead);
// });

// console.log(leadsArr);
